// The Brief card. Renders the most recent terse brief (or any tone
// the dashboard asks for) above For You. Falls back to a "generate
// today's brief" CTA when no brief exists yet.
//
// The brief content is plain text with a fixed shape:
//   TODAY IN ONE SENTENCE
//   <line>
//   HIGHLIGHTS
//   - ...
//   WATCH
//   - ...
// We parse those section headers out and render them as semantic HTML.
// Anything else goes in a small pre block.

import { useEffect, useId, useState } from 'react'
import { api, type Brief } from '../api'

type Props = {
  brief: Brief | null
  onBriefChange: (brief: Brief | null) => void
  // Tone state is lifted to App so the header Brief button + Drawer
  // "Generate brief now" button stay in sync. The card owns its
  // own per-button generating state; the App-level state is separate.
  tone: 'terse' | 'narrative' | 'alert'
  onToneChange: (next: 'terse' | 'narrative' | 'alert') => void
}

// Brief tone options. ``alert`` is auto-generated by source
// convergence (see backend/app/brief.py) — the picker still shows it
// so the surface is discoverable, but the tooltip is honest about it
// being read-only.
const TONES: Array<{ value: 'terse' | 'narrative' | 'alert'; label: string; hint: string }> = [
  { value: 'terse',     label: 'terse',     hint: 'short, dense digest' },
  { value: 'narrative', label: 'narrative', hint: '3-5 sentence newsletter intro' },
  { value: 'alert',     label: 'alert',     hint: 'auto-generated by source convergence — tap to view' },
]

// localStorage key for the collapse preference. Lives alongside the
// other UI keys; no schema version because it's a bare boolean.
const COLLAPSED_KEY = 'brief.collapsed'

// Strip a small set of markdown emphasis chars (``*``, ``_``, ``#``,
// backtick) from the start and end of a line so the parser still
// recognises section headers when the LLM bolds or otherwise marks
// them up. We deliberately don't pull in a markdown library — the
// brief format is fixed and we only need to tolerate a handful of
// mistakes that the backend prompt asks the model not to make.
const EMPHASIS_CHARS_RE = /^[\s*_`#]+|[\s*_`#]+$/g
function stripEmphasis(line: string): string {
  return line.replace(EMPHASIS_CHARS_RE, '')
}

// Strip inline markdown emphasis from a list item body. Handles
// ``**bold**``, ``__bold__``, ``*italic*``, ``_italic_``, and lone
// ```` ` `` `` (backtick). Code spans (``code``) are dropped entirely
// rather than rendered with stray backticks.
const INLINE_EMPHASIS_RE = /(\*\*|__)(.*?)\1/g
const INLINE_ITALIC_RE = /(\*|_)(.*?)\1/g
const INLINE_CODE_RE = /`([^`]*)`/g
function stripInlineEmphasis(text: string): string {
  return text
    .replace(INLINE_EMPHASIS_RE, '$2')
    .replace(INLINE_ITALIC_RE, '$2')
    .replace(INLINE_CODE_RE, '$1')
}

type Parsed = {
  oneSentence: string
  highlights: string[]
  watch: string[]
  remainder: string
}

function parse(content: string): Parsed {
  const out: Parsed = {
    oneSentence: '',
    highlights: [],
    watch: [],
    remainder: '',
  }
  // Defense in depth: even with stop sequences on the backend, a
  // future model or edge case might still emit the prompt-template
  // example (``<one sentence capturing the single most important
  // development>``) or a numbered analysis block before/after the
  // real brief. Truncate the content to the region between the
  // first ``TODAY IN ONE SENTENCE`` header and the end of the last
  // bullet section (``HIGHLIGHTS`` / ``WATCH``). Anything before the
  // first header is prompt-echo noise; anything after a non-bullet
  // line in the WATCH bucket is too.
  const lines = content.split(/\r?\n/)
  // Find the first ``TODAY IN ONE SENTENCE`` line. If we don't find
  // one, the parser already handles it gracefully (everything falls
  // into ``remainder``), so we don't need to fabricate a header.
  let startIdx = lines.findIndex((l) => /^TODAY IN ONE SENTENCE\s*$/i.test(l.trim()))
  if (startIdx === -1) startIdx = 0

  let bucket: 'none' | 'one' | 'high' | 'watch' | 'rest' = 'none'
  for (const raw of lines.slice(startIdx)) {
    // Strip leading/trailing markdown emphasis chars so ``**TODAY IN
    // ONE SENTENCE**`` and ``# TODAY IN ONE SENTENCE`` still match the
    // header regexes below. The bucket transitions happen on the
    // stripped form, but the line content we accumulate is the
    // stripped version too — otherwise ``**headline** — why`` would
    // render with literal asterisks in the dashboard.
    const line = stripEmphasis(raw.trim())
    if (/^TODAY IN ONE SENTENCE/i.test(line)) {
      bucket = 'one'
      continue
    }
    if (/^HIGHLIGHTS/i.test(line)) {
      bucket = 'high'
      continue
    }
    if (/^WATCH/i.test(line)) {
      bucket = 'watch'
      continue
    }
    if (!line) {
      // Blank line — keep bucket, skip.
      continue
    }
    if (bucket === 'one') {
      out.oneSentence = (out.oneSentence ? out.oneSentence + ' ' : '') + line
      bucket = 'rest'
    } else if (bucket === 'high' && line.startsWith('-')) {
      out.highlights.push(stripInlineEmphasis(line.slice(1).trim()))
    } else if (bucket === 'watch' && line.startsWith('-')) {
      out.watch.push(stripInlineEmphasis(line.slice(1).trim()))
    } else if (bucket === 'high' || bucket === 'watch') {
      // Section header detected but no dash — keep accumulating into the
      // first matching list.
      if (bucket === 'high') out.highlights.push(stripInlineEmphasis(line))
      else out.watch.push(stripInlineEmphasis(line))
    } else {
      out.remainder = out.remainder ? out.remainder + '\n' + line : line
    }
  }
  return out
}

function timeAgo(iso: string | null): string {
  if (!iso) return ''
  const ms = Date.now() - new Date(iso).getTime()
  if (ms < 0) return 'just now'
  const mins = Math.floor(ms / 60000)
  if (mins < 1) return 'just now'
  if (mins < 60) return `${mins}m ago`
  const hours = Math.floor(mins / 60)
  if (hours < 24) return `${hours}h ago`
  const days = Math.floor(hours / 24)
  return `${days}d ago`
}

// Tiny tone picker — three pills, one selected. ``alert`` is shown but
// doesn't trigger generation (it'd be a no-op; see TONES hint). The
// picker is ``data-brief-action``-marked so the header click handler
// ignores taps on it (the header is otherwise a collapse toggle — see
// the ``onHeaderClick`` ignore rule above).
function TonePicker({
  tone,
  onToneChange,
  disabled,
}: {
  tone: 'terse' | 'narrative' | 'alert'
  onToneChange: (next: 'terse' | 'narrative' | 'alert') => void
  disabled?: boolean
}) {
  return (
    <div data-brief-action="tone-picker" className="flex items-center gap-1 shrink-0" role="group" aria-label="brief tone">
      {TONES.map((t) => {
        const active = t.value === tone
        return (
          <button
            key={t.value}
            type="button"
            title={t.hint}
            disabled={disabled}
            onClick={(e) => {
              // Stop the header's click handler from also firing
              // (which would collapse the card mid-pick).
              e.stopPropagation()
              onToneChange(t.value)
            }}
            className={`shrink-0 min-h-[28px] rounded-ios px-3 text-ios-body transition disabled:opacity-40 ${
              active
                ? 'bg-bg-elevated text-accent'
                : 'text-label-primary active:bg-bg-elevated'
            }`}
            aria-pressed={active}
          >
            {t.label}
          </button>
        )
      })}
    </div>
  )
}

export function BriefCard({ brief, onBriefChange, tone, onToneChange }: Props) {
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  // Collapse state. Default open; persists per-browser via localStorage
  // so the user doesn't have to re-collapse on every refresh. SSR-safe
  // — the fallback covers the case where window/localStorage isn't
  // available (e.g. an early mount in a future SSR build).
  const [collapsed, setCollapsed] = useState<boolean>(
    () =>
      typeof window !== 'undefined' &&
      window.localStorage?.getItem(COLLAPSED_KEY) === '1',
  )
  const bodyId = useId()

  // Toggle the collapse. Functional setState avoids a stale-closure
  // hazard when two clicks land in the same React batch: each
  // invocation reads the latest state via the updater's argument,
  // not the value captured when this callback was last rendered.
  //
  // The localStorage write lives inside the updater. StrictMode
  // invokes updaters twice in dev; that's harmless here because
  // the writes are idempotent (``'1'`` twice == ``'1'`` once).
  const toggleCollapsed = () => {
    setCollapsed((prev) => {
      const next = !prev
      try {
        window.localStorage?.setItem(COLLAPSED_KEY, next ? '1' : '0')
      } catch {
        // Quota / private-mode failures don't matter — the in-memory
        // state is the source of truth for the current session.
      }
      return next
    })
  }

  // Header-level click handler. Used instead of an absolutely-
  // positioned overlay button so the toggle target is the natural
  // header element, not a duplicate focusable sibling. Clicks that
  // originated from a child interactive element (Regenerate /
  // Generate / the chevron button) carry a sentinel marker; the
  // marker is what lets us avoid the regenerate-then-collapse
  // double-action that ``stopPropagation`` would cause across
  // delegated vs captured handlers.
  const onHeaderClick = (e: React.MouseEvent<HTMLElement>) => {
    const target = e.target as HTMLElement
    // Anything tagged ``data-brief-action`` is an independent
    // control inside the header. Let it act on its own.
    if (target.closest('[data-brief-action]')) return
    toggleCollapsed()
  }

  // Pull latest brief on mount. The parent passes the current value in
  // as a prop so other UI surfaces can refresh it; we only fetch when
  // the prop is null.
  useEffect(() => {
    if (brief) return
    let cancelled = false
    // Latest brief of any tone. We render the tone pill set even if
    // the displayed brief was generated with a different tone — the
    // pills drive what the NEXT regenerate uses, not what we're
    // currently showing.
    api
      .briefLatest({})
      .then((rows) => {
        if (cancelled) return
        if (rows.length > 0) onBriefChange(rows[0])
      })
      .catch(() => {
        // Tolerate 503 etc. — the card just stays in the "no brief" state.
      })
    return () => {
      cancelled = true
    }
  }, [brief, onBriefChange])

  const onGenerate = async () => {
    setError(null)
    setGenerating(true)
    try {
      const next = await api.briefGenerate(tone)
      onBriefChange(next)
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setGenerating(false)
    }
  }

  if (!brief) {
    return (
      <section className="border-b border-hairline bg-bg-app">
        <div
          role="button"
          tabIndex={0}
          aria-expanded={!collapsed}
          aria-controls={bodyId}
          onClick={onHeaderClick}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault()
              toggleCollapsed()
            }
          }}
          className="px-4 py-3 flex items-center gap-3 cursor-pointer select-none min-h-[44px]"
        >
          <span
            aria-hidden="true"
            className="shrink-0 -ml-2 flex items-center justify-center w-11 h-11 rounded-ios text-accent active:bg-bg-elevated"
          >
            <ChevronIcon className="w-4 h-4" collapsed={collapsed} />
          </span>
          <div className="flex-1 min-w-0">
            <h2 className="text-ios-caption uppercase tracking-wide text-label-tertiary">
              The Brief
            </h2>
            {!collapsed && (
              <p className="text-ios-body text-label-secondary mt-0.5">
                No brief generated yet for today.
              </p>
            )}
          </div>
          {/* Tone picker — drives the next generate. Visible on
              both states (with / without brief) so the user can
              pre-pick a tone before clicking Generate. */}
          <TonePicker
            tone={tone}
            onToneChange={onToneChange}
            disabled={generating}
          />
          {/* Generate button — independent action, marked so the
              header click handler ignores taps on it. min-h-[44px]
              keeps the touch target large enough for a thumb. */}
          <button
            data-brief-action="generate"
            onClick={onGenerate}
            disabled={generating}
            className="shrink-0 min-h-[44px] rounded-ios px-3 text-ios-body text-accent active:bg-bg-elevated disabled:opacity-40"
          >
            {generating ? '…' : "Generate"}
          </button>
        </div>
        {!collapsed && error && (
          <p className="px-4 pb-3 text-ios-caption text-red-400">{error}</p>
        )}
      </section>
    )
  }

  const parsed = parse(brief.content)

  return (
    <section className="border-b border-hairline bg-bg-app">
      {/* Header row. The whole element is the toggle target — chevron,
          title, tone badge, timestamp — but Regenerate is a child
          marked ``data-brief-action`` so it bypasses the toggle. */}
      <header
        role="button"
        tabIndex={0}
        aria-expanded={!collapsed}
        aria-controls={bodyId}
        onClick={onHeaderClick}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            toggleCollapsed()
          }
        }}
        className="flex flex-wrap items-center gap-x-2 gap-y-2 px-4 pt-3 pb-2 cursor-pointer select-none"
      >
        <span
          aria-hidden="true"
          className="shrink-0 -ml-2 flex items-center justify-center w-11 h-11 rounded-ios text-accent active:bg-bg-elevated"
        >
          <ChevronIcon className="w-4 h-4" collapsed={collapsed} />
        </span>
        <h2 className="text-ios-caption uppercase tracking-wide text-label-tertiary shrink-0">
          The Brief
        </h2>
        {/* "TODAY'S BRIEF" pill. Anchors the brief as a
            recognizable recurring surface — same idea as a
            newsletter masthead — without committing to a date
            string (which would need to update daily). The pill
            sits inline next to the title; on mobile it wraps
            naturally. */}
        <span
          data-brief-action="today-pill"
          className="inline-flex items-center gap-1 rounded-full bg-accent-soft px-2 py-0.5 text-ios-caption uppercase tracking-wide text-accent shrink-0"
          title="the most recent brief"
        >
          <span aria-hidden="true" className="h-1.5 w-1.5 rounded-full bg-accent" />
          today's
        </span>
        {/* Tone picker replaces the static tone badge — the badge
            was informational, the picker is the same surface turned
            interactive. ``shrink-0`` so it never collapses into a
            segmented nub when other chrome on the row widens. */}
        <TonePicker
          tone={tone}
          onToneChange={onToneChange}
          disabled={generating}
        />
        {/* Trailing chrome (timestamp + Regenerate) sits on its own
            row on mobile so it can't collide with the tone picker
            or the "today's" pill. On ``sm+`` it's ``ml-auto`` so it
            floats to the right edge of the same first row. The
            conditional ``sm:ml-auto sm:basis-auto`` resets the
            mobile behaviour (where we want it on its own line). */}
        <div className="flex items-center gap-2 text-ios-caption text-label-secondary shrink-0 basis-full sm:basis-auto sm:ml-auto">
          <span title={brief.generated_at}>
            {/* "generated " prefix only on sm+; saves ~70px on mobile
                so the Regenerate button isn't pushed off-screen. */}
            <span className="hidden sm:inline">generated </span>
            {timeAgo(brief.generated_at)}
          </span>
          <button
            data-brief-action="regenerate"
            onClick={onGenerate}
            disabled={generating}
            className="min-h-[36px] rounded-ios px-3 text-ios-body text-accent active:bg-bg-elevated disabled:opacity-40"
          >
            {generating ? '…' : 'Regenerate'}
          </button>
        </div>
      </header>
      {!collapsed && (
        <div id={bodyId} className="px-4 pb-3 space-y-2">
          {/* One-sentence hero. Larger than the original body text
              so the brief's "headline" lands with weight — this is
              what the user reads first, and it's the line the model
              was asked to write most carefully. */}
          {parsed.oneSentence && (
            <p className="text-lg sm:text-xl font-semibold leading-snug text-label-primary">
              {parsed.oneSentence}
            </p>
          )}
          {parsed.highlights.length > 0 && (
            <ul className="space-y-1.5 text-ios-body text-label-primary list-none">
              {parsed.highlights.map((h, i) => (
                // Accent dot replaces the text bullet. ``items-start``
                // so the dot sits aligned to the first line of the
                // text even when the highlight wraps to two lines.
                <li key={i} className="flex items-start gap-2">
                  <span
                    aria-hidden="true"
                    className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent"
                  />
                  <span>{h}</span>
                </li>
              ))}
            </ul>
          )}
          {parsed.watch.length > 0 && (
            <div className="pt-1">
              <h3 className="text-ios-caption uppercase tracking-wide text-label-tertiary mb-1">
                Watch
              </h3>
              <ul className="space-y-0.5 text-ios-caption text-label-secondary list-none">
                {parsed.watch.map((w, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span
                      aria-hidden="true"
                      className="mt-1 h-1 w-1 shrink-0 rounded-full bg-label-tertiary"
                    />
                    <span>{w}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          {/* The remainder block is no longer rendered. In practice
              it has only ever shown leaked prompt-template text
              (e.g. "Source Material:", "Analyze the Request:") that
              the backend should have prevented via stop sequences.
              If a future model emits useful prose that doesn't fit
              the schema, the right place to surface it is here —
              but it should require explicit opt-in (a flag on the
              parsed result, e.g. ``parsed.hasUsefulRemainder``)
              rather than render any leftover text by default. */}
          {error && <p className="text-ios-caption text-red-400">{error}</p>}
        </div>
      )}
    </section>
  )
}

// Small chevron used as the BriefCard expand/collapse indicator.
// Rendered with a single CSS transform so the animation is purely
// GPU-driven and feels native.
function ChevronIcon({ className, collapsed }: { className?: string; collapsed?: boolean }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.75}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={`${className ?? ''} transition-transform duration-200 ${collapsed ? '' : 'rotate-90'}`}
      aria-hidden="true"
    >
      <polyline points="9 6 15 12 9 18" />
    </svg>
  )
}